export const DEPARTMENT_KEYWORDS: Record<string, string[]> = {
  IT: [
    'wifi',
    'login',
    'password',
    'portal',
    'account',
    'network',
    'vpn',
    'email',
    'software',
    'computer',
  ],
  Maintenance: [
    'leak',
    'heater',
    'broken',
    'repair',
    'facility',
    'electricity',
    'plumbing',
    'room',
    'furniture',
    'ac',
    'air conditioning',
  ],
  Finance: [
    'tuition',
    'payment',
    'invoice',
    'refund',
    'fee',
    'scholarship',
    'bill',
    'transfer',
    'financial aid',
  ],
  Academics: [
    'exam',
    'grade',
    'course',
    'professor',
    'registration',
    'curriculum',
    'class',
    'transcript',
    'credit',
  ],
};
